// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestApi.Data;

namespace TestApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("TestApi.Models.Face", b =>
                {
                    b.Property<int>("FaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttrAge")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttrBeauty")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthType")
                        .HasColumnType("TEXT");

                    b.Property<string>("CardNum")
                        .HasColumnType("TEXT");

                    b.Property<string>("CertificateNumber")
                        .HasColumnType("TEXT");

                    b.Property<int>("CertificateType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CommonUuid")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ethic")
                        .HasColumnType("TEXT");

                    b.Property<double>("FaceTemperature")
                        .HasColumnType("REAL");

                    b.Property<string>("Gender")
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<string>("Irimg")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Orgimg")
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonUuid")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlateId")
                        .HasColumnType("TEXT");

                    b.Property<string>("QRcode")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ScanDatasScanId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ScanId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Similarity")
                        .HasColumnType("REAL");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<string>("TemperatureAlarm")
                        .HasColumnType("TEXT");

                    b.Property<long>("Timestamp")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrackId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("FaceId");

                    b.HasIndex("ScanDatasScanId");

                    b.ToTable("Faces");
                });

            modelBuilder.Entity("TestApi.Models.ScanData", b =>
                {
                    b.Property<int>("ScanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Camid")
                        .HasColumnType("TEXT");

                    b.Property<string>("Devid")
                        .HasColumnType("TEXT");

                    b.Property<string>("Devmac")
                        .HasColumnType("TEXT");

                    b.Property<string>("Devname")
                        .HasColumnType("TEXT");

                    b.Property<string>("Devno")
                        .HasColumnType("TEXT");

                    b.Property<string>("Event")
                        .HasColumnType("TEXT");

                    b.Property<string>("Operator")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Time")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Timelocal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("ScanId");

                    b.ToTable("ScanDatas");
                });

            modelBuilder.Entity("TestApi.Models.Face", b =>
                {
                    b.HasOne("TestApi.Models.ScanData", "ScanDatas")
                        .WithMany("Faces")
                        .HasForeignKey("ScanDatasScanId");

                    b.Navigation("ScanDatas");
                });

            modelBuilder.Entity("TestApi.Models.ScanData", b =>
                {
                    b.Navigation("Faces");
                });
#pragma warning restore 612, 618
        }
    }
}
